[root]
url = "http://lovebear.top/info"
title = "SRC信息收集导航。lovebear.top/info"
desc = "SRC信息收集导航。lovebear.top/info"
image = "http://lovebear.top/info/assets/images/webstack_banner_cn.png"

[navigator]
[navigator.域名信息]

[[navigator.域名信息.Whois 查询]]

url = "hjj"